### PR TITLE
Don't set input default values to null

### PR DESCRIPTION
**Pull request by bconnorwhite**
TODO:

- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests and linter rules pass

### CODE REVIEW

**Review by yaacovCR — COMMENTED** [review]
Thanks for submitting a pull request!

Looks like this refactoring streamlines some code, but functionality unchanged. Is that about right?

But you have me worried there may be a bug lurking somewhere. Is anything breaking for you?

**Comment by bconnorwhite** [comment]
The difference is between `==` and `===`

Since we are comparing `if(value == null)` (not ===), if `value` is undefined, the default will be changed from undefined to null:

```
if (value == null) {
  return null;
}
```
Results in:
`field(input: Type = null): ReturnType` -> `field(input: Type = null): ReturnType` ✅
`field(input: Type): ReturnType` -> `field(input: Type = null): ReturnType` ❌

Whereas:
```
if (value == null) {
  return value;
}
```
Results in:
`field(input: Type = null): ReturnType` -> `field(input: Type = null): ReturnType` ✅
`field(input: Type): ReturnType` -> `field(input: Type): ReturnType` ✅


This causes issues with input types like this:
```
type UserWhereInput {
  attribute1: value,
  attribute2: value,
  attribute3: value
}
```
Say if an attribute is included, I want to return users with the matching value. If the default for each attribute is set to null, now I end up checking attribute2 == null and attribute3 == null even if I left those out of my query and just want to check equality on attribute1:
```
users(where: { attribute1: X }) {
  ...
}
```

**Comment by yaacovCR** [comment]
Got it. Looks good to me. Will merge as soon as I can. Thanks!

**Comment by yaacovCR** [comment]
Merged as v6.3.3.

**Pull request merged**
