### PR TITLE
GraphQL v15 support

### PR DESCRIPTION
**Pull request by ardatan**
- Do not extend if the node is already extended (GraphQL v15 does that internally)
- Do not use `introspectionQuery` which is deprecated and removed in v15
- Fix asyncIterator typing

### CODE REVIEW

**Comment by yaacovCR** [comment]
See #32 

Do you have any suggestions for supporting both v14 and v15. I imagine I will need to release a major version change (I am up to v8.5, so v9?) with the changes from #32 and then would have to backport any fixes to a V8 branch.

**Comment by ardatan** [comment]
I think those changes already support both v14 and v15. They are not only for v15.
`getIntrospectionQuery` is already introduced in v14, and changes about extensions check if extensions are included in actual astNode not to break anything on v14.

**Comment by yaacovCR** [comment]
I think because there are breaking changes anyway between v14 and v15 that it is better/cleaner to fix extensions issues as in https://github.com/yaacovCR/graphql-tools-fork/commit/a3aadcf368b6495c03c73cf6ae613222b3acede3 rather than with check for existence of extension nodes after buildSchema. Do you disagree?

**Comment by yaacovCR** [comment]
See also #40

**Comment by ardatan** [comment]
I think those changes can be applied for both v14 and v15. I think supporting both versions would be better than having different releases for each. @yaacovCR

**Comment by yaacovCR** [comment]
This is addressed in graphql-tools-fork v8.6.0 which supports:
graphql v14.2.0 and above
graphql v15.0.0-rc2 and above

**Pull request closed without merging**
